version: '3.9'
services:
  my_app:
    build: .
    image: uit-docker-app
    container_name: uit-docker-app
    ports:
      - "9000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - default
      - zerotier

  mongo:
    image: mongo:latest
    container_name: uit-mongo-db
    ports:
      - "27000:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - default
      - zerotier

volumes:
  mongo_data:

networks:
  app_network:
    driver: bridge

  zerotier_network:
    external: true
    driver_opts:
      com.docker.network.bridge.name: "zt-subnet" 
    ipam:
      driver: default
      config:
        - subnet: 172.26.0.0/16